"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name, default=0):
    value = os.getenv(name)
    if value is None or value.strip() == "":
        return default
    return int(value)


def env_list(name, default=None):
    value = os.getenv(name)
    if value is None:
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]


RUNNING_TESTS = "test" in sys.argv
DEBUG = env_bool("DEBUG", default=True)
DEFAULT_LOCAL_HOSTS = ["localhost", "127.0.0.1", "[::1]", "testserver"]
DEFAULT_LOCAL_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
]

SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-only-insecure-secret-key"
    else:
        raise ImproperlyConfigured("SECRET_KEY must be set when DEBUG is False.")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-vx!s%l^-8tv17@!rhqjxs$a1l8o5kq!ws%v^jga*=4x-=xi3!1'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    default=DEFAULT_LOCAL_HOSTS if DEBUG else [],
)
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured("ALLOWED_HOSTS must be set when DEBUG is False.")

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    default=DEFAULT_LOCAL_ORIGINS if DEBUG else [],
)
CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    default=DEFAULT_LOCAL_ORIGINS if DEBUG else [],
)

CORS_ALLOW_CREDENTIALS = True
# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.postgres',
    'rest_framework_simplejwt.token_blacklist',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_q',
    'accounts',
    'cycles',
    'notifications',
    'templates_mgmt',
    'dashboard',
]

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "password_reset": os.getenv("PASSWORD_RESET_THROTTLE_RATE", "5/hour"),
        "password_reset_confirm": os.getenv("PASSWORD_RESET_CONFIRM_THROTTLE_RATE", "10/hour"),
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

AUTH_SESSION_INACTIVITY_TIMEOUT = timedelta(minutes=30)

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

ENABLE_HTTPS_SECURITY = not DEBUG and not RUNNING_TESTS
SECURE_SSL_REDIRECT = ENABLE_HTTPS_SECURITY and env_bool(
    "SECURE_SSL_REDIRECT",
    default=True,
)
SESSION_COOKIE_SECURE = ENABLE_HTTPS_SECURITY and env_bool(
    "SESSION_COOKIE_SECURE",
    default=True,
)
CSRF_COOKIE_SECURE = ENABLE_HTTPS_SECURITY and env_bool(
    "CSRF_COOKIE_SECURE",
    default=True,
)
SECURE_HSTS_SECONDS = (
    env_int("SECURE_HSTS_SECONDS", default=0) if ENABLE_HTTPS_SECURITY else 0
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = (
    SECURE_HSTS_SECONDS > 0
    and env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
)
SECURE_HSTS_PRELOAD = (
    SECURE_HSTS_SECONDS > 0
    and env_bool("SECURE_HSTS_PRELOAD", default=False)
)
if env_bool("USE_X_FORWARDED_PROTO", default=False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", default=True)

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
PASSWORD_RESET_TIMEOUT = 60 * 10


# django-q2, background job runner (mark_overdue_tasks, Module 9).
# Uses the ORM broker, so no extra infrastructure (Redis etc) is needed,
# it reuses the Postgres connection already configured above. This makes
# django-q2 usable, it does not by itself run anything: a worker process
# (`python manage.py qcluster`) still has to be running continuously
# somewhere for scheduled jobs to actually fire. See
# cycles/SCHEDULER_SETUP.md for the deployment steps once hosting is
# decided (NFR-6.4 requires this to work on both Linux and Windows).
Q_CLUSTER = {
    "name": "recurra",
    "workers": int(os.getenv("Q_CLUSTER_WORKERS", 2)),
    "recycle": 500,
    "timeout": 60,
    "retry": 90,
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
}

FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173").rstrip("/")


# Logging settings
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "standard": {
            "format": (
                "%(asctime)s | "
                "%(levelname)s | "
                "%(name)s | "
                "%(message)s"
            ),
        },
    },

    "handlers": {
        "email_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "emails.log",
            "formatter": "standard",
        },
    },

    "loggers": {
        "emails": {
            "handlers": ["email_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
