# Generated by Django 6.0.5 on 2026-06-22 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates_mgmt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleInstance',
            fields=[
                ('cycle_id', models.AutoField(primary_key=True, serialize=False)),
                ('cycle_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('shut_down', 'Shut Down')], default='running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_instances', to='templates_mgmt.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_instances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CycleActivity',
            fields=[
                ('cycle_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100)),
                ('calculated_start_date', models.DateField()),
                ('calculated_end_date', models.DateField()),
                ('note_text', models.TextField(blank=True, null=True)),
                ('template_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_activities', to='templates_mgmt.templateactivity')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_activities', to='cycles.cycleinstance')),
            ],
        ),
        migrations.CreateModel(
            name='CycleTask',
            fields=[
                ('cycle_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('calculated_start_date', models.DateField()),
                ('calculated_end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('delayed', 'Delayed')], default='pending', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_fixed_date', models.BooleanField(default=False)),
                ('reminder_lead_days', models.PositiveIntegerField(blank=True, null=True)),
                ('note_text', models.TextField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_tasks', to='cycles.cycleinstance')),
                ('template_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_tasks', to='templates_mgmt.templatetask')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('dependency_id', models.AutoField(primary_key=True, serialize=False)),
                ('dependency_depth', models.PositiveIntegerField(default=1)),
                ('depends_on_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_tasks', to='templates_mgmt.templatetask')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='templates_mgmt.templatetask')),
            ],
        ),
    ]
