# Generated by Django 6.0.5 on 2026-06-23 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_current_version',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='template',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='templates_mgmt.template'),
        ),
    ]
