# Generated by Django 6.0.5 on 2026-06-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mgmt', '0002_template_is_current_version_template_parent_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('task_dependency_id', models.AutoField(primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(default='finish_to_start', max_length=30)),
            ],
        ),
        migrations.AddConstraint(
            model_name='templateactivitytag',
            constraint=models.UniqueConstraint(fields=('template_activity', 'tag'), name='unique_template_activity_tag'),
        ),
        migrations.AddConstraint(
            model_name='templatetasktag',
            constraint=models.UniqueConstraint(fields=('template_task', 'tag'), name='unique_template_task_tag'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='dependent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_links', to='templates_mgmt.templatetask'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='predecessor_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_links', to='templates_mgmt.templatetask'),
        ),
    ]
