# Generated by Django 6.0.5 on 2026-06-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mgmt', '0003_taskdependency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDependency',
        ),
    ]
