# Generated by Django 6.0.5 on 2026-07-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mgmt', '0003_alter_templateactivity_options_and_more'),
        ('templates_mgmt', '0005_alter_templatetask_reminder_lead_days'),
    ]

    operations = [
    ]
