# Generated by Django 6.0.5 on 2026-07-09 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mgmt', '0006_merge_20260709_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetask',
            name='template_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_tasks', to='templates_mgmt.templateactivity'),
        ),
    ]
