# Generated by Django 6.0.5 on 2026-07-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mgmt', '0006_merge_20260710_2001'),
        ('templates_mgmt', '0007_templatetask_template_activity'),
    ]

    operations = [
    ]
