# Generated by Django 6.0.5 on 2026-07-13 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mgmt', '0007_templatetask_template_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'tag_name'), name='unique_user_tag_name'),
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='templates_mgmt.templatecategory'),
        ),
        migrations.AddConstraint(
            model_name='templatecategory',
            constraint=models.UniqueConstraint(fields=('user', 'category_name'), name='unique_user_category_name'),
        ),
    ]