# Generated by Django 6.0.5 on 2026-07-05 12:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_alter_cycletask_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    DECLARE
                        constraint_name text;
                    BEGIN
                        FOR constraint_name IN
                            SELECT conname
                            FROM pg_constraint
                            WHERE conrelid = 'cycles_cycletask'::regclass
                            AND pg_get_constraintdef(oid) LIKE '%reminder_lead_days%'
                        LOOP
                            EXECUTE 'ALTER TABLE cycles_cycletask DROP CONSTRAINT ' || quote_ident(constraint_name);
                        END LOOP;
                    END $$;

                    ALTER TABLE cycles_cycletask
                    ALTER COLUMN reminder_lead_days
                    TYPE integer[]
                    USING CASE
                        WHEN reminder_lead_days IS NULL THEN ARRAY[]::integer[]
                        ELSE ARRAY[reminder_lead_days]
                    END;
                    """,
                    reverse_sql="""
                    ALTER TABLE cycles_cycletask
                    ALTER COLUMN reminder_lead_days
                    TYPE integer
                    USING CASE
                        WHEN reminder_lead_days IS NULL OR array_length(reminder_lead_days, 1) IS NULL
                        THEN NULL
                        ELSE reminder_lead_days[1]
                    END;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="cycletask",
                    name="reminder_lead_days",
                    field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
