# Generated by Django 6.0.5 on 2026-07-08 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0003_alter_cycletask_reminder_lead_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletask',
            name='cycle_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_tasks', to='cycles.cycleactivity'),
        ),
    ]
