# Generated by Django 6.0.5 on 2026-07-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_alter_cycletask_reminder_lead_days'),
        ('cycles', '0003_alter_cycletask_reminder_lead_days'),
    ]

    operations = [
    ]
