# Generated by Django 6.0.5 on 2026-07-09 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0004_merge_20260709_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletask',
            name='cycle_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_tasks', to='cycles.cycleactivity'),
        ),
    ]
