# Generated by hand on 2026-07-14
#
# Deleting a Template used to cascade-delete every CycleInstance (and
# in turn every CycleTask/CycleActivity) ever created from it — a
# user intentionally deleting an old template silently wiped out the
# history of every cycle that had ever run from it. These three
# fields switch from CASCADE to SET_NULL: the cycle rows survive,
# only the now-meaningless link back to the deleted template row is
# cleared. See TemplateViewSet.destroy in templates_mgmt/views.py,
# which also shuts down any still-running cycle before the delete.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0005_cycletask_cycle_activity'),
        ('templates_mgmt', '0008_templatecategory_tag_unique_user_tag_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycleinstance',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_instances', to='templates_mgmt.template'),
        ),
        migrations.AlterField(
            model_name='cycletask',
            name='template_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_tasks', to='templates_mgmt.templatetask'),
        ),
        migrations.AlterField(
            model_name='cycleactivity',
            name='template_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_activities', to='templates_mgmt.templateactivity'),
        ),
    ]