# Generated by Django 6.0.5 on 2026-06-20 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('template_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by_type', models.CharField(default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateActivity',
            fields=[
                ('template_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_offset_days', models.PositiveIntegerField()),
                ('end_offset_days', models.PositiveIntegerField()),
                ('note_text', models.TextField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_activities', to='templates_mgmt.template')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateActivityTag',
            fields=[
                ('template_activity_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates_mgmt.tag')),
                ('template_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates_mgmt.templateactivity')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateTask',
            fields=[
                ('template_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('day_offset', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_fixed_date', models.BooleanField(default=False)),
                ('reminder_lead_days', models.PositiveIntegerField(blank=True, null=True)),
                ('note_text', models.TextField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_tasks', to='templates_mgmt.template')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateTaskTag',
            fields=[
                ('template_task_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates_mgmt.tag')),
                ('template_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates_mgmt.templatetask')),
            ],
        ),
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('user_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('owner', 'Owner'), ('saved', 'Saved'), ('shared', 'Shared')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates_mgmt.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
